name: Bearworking
on:
  push:
    branches:
      - 'release/v[0-9].[0-9]'
      - 'release/v[0-9][0-9].[0-9]'
jobs: 
  My_First:
    runs-on: ubuntu-latest
    if: startsWith( github.event.head_commit.message , '#NORUN') != true 
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'YSKabcdef/BearLeroyTan'
    - uses: bervProject/railway-deploy@main
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: "tame-furniture"

    - run: echo ${{secrets.RAILWAY_TOKEN}}
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # This data can be any valid JSON from a previous step in the GitHub Action
        payload: |
          
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "DipSA 56 CI/CD Submission",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Name:* ${{vars.NAME}}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Email:* ${{vars.EMAIL}}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Metriculation:* ${{vars.MATNUMBER}}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:* ${{ github.server_url }}/${{ github.repository }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{vars.URL}}"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Go",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "${{vars.URL}}",
                    "action_id": "button-action"
                  }
                }
              ]
            }
          
        
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        