name: Bearworking
on:
  push:
    branches:
      - 'release/v[0-9].[0-9]'
      - 'release/v[0-9][0-9].[0-9]'
jobs: 
  My_First:
    runs-on: ubuntu-latest
    if: startsWith( github.event.head_commit.message , '#NORUN') != true 
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'YSKabcdef/BearLeroyTan'
    - uses: bervProject/railway-deploy@main
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: "tame-furniture"

    - run: echo ${{secrets.RAILWAY_TOKEN}}
    #- name: Send custom JSON data to Slack workflow
     # id: slack
      #uses: slackapi/slack-github-action@v1.23.0
      #with:
      # For posting a rich message using Block Kit
      #  payload: |
          #{
            #"text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            #"blocks": [
          #{
            #"type": "section",
            #"text": {
           #   "type": "mrkdwn",
          #    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
           #         }
            #        }
            #]
         #}
      # env:
        #SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        #SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK 
