name: Bearworking
on:
  push:
    branches:
    - ['feature/v[0-9].[0-9]?']
    - ['feature/v[0-9][0-9].[0-9]?']
jobs: 
  My_First:
    runs-on: ubuntu-latest
    steps: 
    - name: test
      run: echo date
