name: Bearworking
on:
  push:
    branches:
      - 'release/v[0-9].[0-9]'
      - 'release/v[0-9][0-9].[0-9]'
jobs: 
  My_First:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
      with:
        repository: 'https://github.com/YSKabcdef/BearLeroyTan.git'
    - uses: bervProject/railway-deploy@main
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: "tame-furniture"

